language: python
sudo: required
python:
  - "2.7"

script:
  bash build.sh

after_success:
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file_glob: true
  file:
    dist/*.tar.bz2
  skip_cleanup: true
  on:
    tags: true
